/**
 * Generates redirect configuration for CloudFront Function.
 *
 * Usage: pnpm exec ts-node --esm scripts/generate-s3-redirects.ts
 *
 * Outputs:
 *   - deploy/terraform/cloudfront-redirects.js (CloudFront Function code)
 *   - deploy/terraform/s3-routing-rules.json (legacy, kept for reference)
 */

import { allPosts } from '../.content-collections/generated/index.js'
import * as fs from 'node:fs'
import * as path from 'node:path'

interface RedirectRule {
  prefix: string
  target: string
}

const rules: RedirectRule[] = []

// Generate redirects for imported Tumblr posts
for (const post of allPosts) {
  if (post.tumblrId) {
    rules.push({
      prefix: `post/${post.tumblrId}`,
      target: `articles/${post.slug}/`,
    })
  }
}

// Add static redirects
rules.push(
  { prefix: 'rss', target: 'feed.xml' },
  { prefix: 'archive', target: 'articles/' }
)

// Generate CloudFront Function code
const cloudFrontFunctionCode = `// CloudFront Function for URL redirects
// Auto-generated by scripts/generate-s3-redirects.ts
// Do not edit directly - run: pnpm generate:redirects

var redirects = {
${rules.map((r) => `  '${r.prefix}': '${r.target}'`).join(',\n')}
};

function handler(event) {
  var request = event.request;
  var uri = request.uri;

  // Remove leading slash for matching
  var path = uri.substring(1);

  // Check for exact prefix matches
  for (var prefix in redirects) {
    if (path === prefix || path.startsWith(prefix + '/')) {
      var target = redirects[prefix];
      return {
        statusCode: 301,
        statusDescription: 'Moved Permanently',
        headers: {
          'location': { value: '/' + target },
          'cache-control': { value: 'max-age=3600' }
        }
      };
    }
  }

  // Add index.html for directory requests (no extension)
  if (uri.endsWith('/')) {
    request.uri += 'index.html';
  } else if (!uri.includes('.')) {
    // No extension - try adding /index.html
    request.uri += '/index.html';
  }

  return request;
}
`

// Write CloudFront Function code
const cfFunctionPath = path.join(
  import.meta.dirname,
  '../deploy/terraform/cloudfront-redirects.js'
)
fs.writeFileSync(cfFunctionPath, cloudFrontFunctionCode)

// Also write legacy S3 routing rules JSON (for reference)
interface S3RoutingRule {
  Condition: { KeyPrefixEquals: string }
  Redirect: {
    HttpRedirectCode: string
    ReplaceKeyWith: string
  }
}

const s3Rules: S3RoutingRule[] = rules.map((r) => ({
  Condition: { KeyPrefixEquals: r.prefix },
  Redirect: {
    HttpRedirectCode: '301',
    ReplaceKeyWith: r.target,
  },
}))

const s3RulesPath = path.join(
  import.meta.dirname,
  '../deploy/terraform/s3-routing-rules.json'
)
fs.writeFileSync(s3RulesPath, JSON.stringify(s3Rules, null, 2))

console.log(`Generated ${rules.length} redirect rules`)
console.log(`CloudFront Function: ${cfFunctionPath}`)
console.log(`S3 Routing Rules (legacy): ${s3RulesPath}`)
console.log('')
console.log('Redirects:')
for (const rule of rules) {
  console.log(`  /${rule.prefix}* -> /${rule.target}`)
}
